theme: jekyll-theme-slate

title: Nadica Miljković
description: Professor <br />University of Belgrade - School of Electrical Engineering and Visiting Researcher <br />Faculty of Electrical Engineering, University of Ljubljana

#show_downloads: true
google_analytics:
