theme: jekyll-theme-slate

title: Nadica Miljković
description: Professor at the University of Belgrade - School of Electrical Engineering and <br />Visiting Researcher at the Faculty of Electrical Engineering, University of Ljubljana

#show_downloads: true
google_analytics:
